be/src/main/java/codesquad/bookkbookk/config/FilterConfig.java, be/src/main/java/codesquad/bookkbookk/error/ApiExceptionHandler.java, be/src/main/java/codesquad/bookkbookk/error/exception/ApiException.java, be/src/main/java/codesquad/bookkbookk/error/exception/ErrorResponse.java, be/src/main/java/codesquad/bookkbookk/error/exception/MemberNotFoundException.java, be/src/main/java/codesquad/bookkbookk/filter/CorsFilter.java, be/src/main/java/codesquad/bookkbookk/filter/JwtFilter.java, be/src/main/java/codesquad/bookkbookk/jwt/JwtProvider.java, be/src/main/java/codesquad/bookkbookk/member/controller/MemberController.java, be/src/main/java/codesquad/bookkbookk/member/service/MemberService.java, be/src/main/java/codesquad/bookkbookk/resolver/JwtArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/resolver/MemberId.java, be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java, be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
ArgumentResolver, ExceptionHandler, Filter 등 프로그램의 전반에 필요한 클래스를 작성했습니다.
- JwtArgumentResolver: 기존에 Jwt를 Controller에서 파싱했었는데, 코드의 중복을 줄여 가독서을 높이고자 어노테이션으로 주입할 수 있게 했습니다.
- ApiException: RuntimeException을 상속하는 클래스로, 프로그램 로직상의 예외를 정의하기 위해 만들었습니다. 앞으로 만들어지는 모든 예외는 이 예외를 상속받아서 만들 생각입니다.
- ExceptionHandler: ApiException을 잡아 ErrorResponse로 변환합니다.
- ErrorResponse: ApiException을 바로 ResponseEntity에 넣어 응답으로 줄 경우 필요없는 정보들이 들어가게 됩니다. 따라서 필요한 정보만 전달하기 위해 도입했습니다.
코드 스타일도 바꿔야하고 패키지 구조도 바꿔야 하는데 그건 일단 감귤이 작업하고 있는거 마무리 하면 변경하겠습니다.
=> [BE]: 프로그램에 필요한 공통 코드 작성

be/src/main/java/codesquad/bookkbookk/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/CreateBookClubRequest.java, be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/CreateBookClubResponse.java, be/src/main/java/codesquad/bookkbookk/bookclub/data/dto/ReadBookClubResponse.java, be/src/main/java/codesquad/bookkbookk/bookclub/data/entity/BookClub.java, be/src/main/java/codesquad/bookkbookk/bookclub/data/entity/MemberBookClub.java, be/src/main/java/codesquad/bookkbookk/bookclub/repository/BookClubRepository.java, be/src/main/java/codesquad/bookkbookk/bookclub/repository/MemberBookClubRepository.java, be/src/main/java/codesquad/bookkbookk/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/member/data/entity/Member.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
-북클럽 생성
-현재 로그인한 회원이 속한 북클럽 조회
- 현재 북클럽 조회를 토큰을 파싱하여 해당 멤버가 속한 북클럽만 응답하도록 했습니다
- 이유는 북클럽을 관리하기 위한 웹이라고 생각해서 가입은 초대 방식으로 하고, 소속된 북클럽만 보여주는게 좋지 않을까 생각했습니다.
- 에러 핸들링 미구현이라 나그 코드 머지되면 수정해야 할 것 같아요!
=> [BE] 북클럽 생성, 조회 기능 구현

be/src/main/java/codesquad/bookkbookk/common/error/exception/AccessDeniedBookClubError.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/BookClubNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/BookNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberNotInBookClubException.java, be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/BookClubBook.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookClubBookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/MemberBookClubRepository.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
- 책, 북클럽의 책 엔티티 구현
- 책 추가 기능 구현
- 책 추가 성공 테스트 케이스 구현
- 북클럽에 책 추가시, 북클럽의 회원이 아닐 경우 에러를 던지도록 만들었습니다. 나중에 권한이 더 구체화 되면 권한으로 다뤄도 좋을 것 같아요
- 'BookClubBook' 네이밍이 개인적으로 좀 별로인 것 같은 기분이 많이 들었어요  의견이 궁금합니다
=> [BE] 책 추가 기능 구현 #15

be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
- 북클럽 생성 요청 프로필 이미지 NULL 조회
- NULL일 경우 디폴트 이미지로 생성
=> [BE] 북클럽 생성 시 이미지 null일 경우 디폴트 이미지 추가

be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java
- Book Entity id -> isbn
- 요청 시 받은 isbn이 repo에 이미 있을 경우 save를 하지 않음
=> [BE] book entity id isbn으로 변경 및 검증 로직 구현

be/src/main/java/codesquad/bookkbookk/domain/book/controller/AladinController.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadAladinBooksResponse.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/AladinService.java, be/src/test/java/codesquad/bookkbookk/aladin/integration/AladinTest.java
- 알라딘 open api 책 검색 기능 구현
- 커밋 보시면 아시겠지만 response DTO 필드가 final이 아닐 때, 동작은 잘 되는데 RestAssured 테스트를 진행하면 jsonPath().getList("", 응답.class) 부분에서 역직렬화 에러가 나더라고요. 이유는 아직 모르겠습니다
=> [BE] 알라딘 책 검색 기능 구현

be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookResponse.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/MemberBook.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/MemberBookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- MemberBook Entity 구현
- 나의 책 목록 조회 기능 구현
- 테스트 성공 케이스 구현
- 책 조회 시, 이름 기준 오름차순, slice로 구현했습니다. Page가 아닌 Slice로 구현한 이유는 스크롤로 조회만 할 뿐, 전체 데이터 개수를 알 필요가 없을 것 같아서 slice로 구현했습니다!
- 응답에 hasNext 변수를 포함하기 위해, Response DTO에 책의 정보를 담는 이너 클래스를 사용했습니다.
=> [BE] 나의 책 목록 조회 기능 구현

be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/auth/repository/MemberRefreshTokenRepository.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/OAuthService.java, be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
로그아웃 기능을 구현했습니다.
간단하게 구현하기 위해서 레포지토리에 deleteByMemberId() 메서드를 생성하고 삭제했습니다.
목요일날 올거죠?
=> [BE]: 로그아웃 기능 구현

be/src/main/java/codesquad/bookkbookk/common/error/exception/InvitationUrlNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/CreateInvitationUrlRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/InvitationUrlResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClubInvitationUrl.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubInvitationUrlRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubInvitationService.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubInvitationTest.java
- 북클럽 초대 url 생성
- 북클럽 초대 url 조회
- 테스트 코드
- 제가 구현하면서 생각한 초대 링크 받아오는 flow는
- 북클럽 생성과 동시에 프론트에서 초대 링크 api를 요청한다. 이후는 조회만 한다.
- 먼저 조회 요청을 보낸 다음에, NotFound 예외가 발생하면 생성 요청을 한다.
이 두 개로 생각하면서 코드를 작성했습니다..
=> [BE] 북클럽 초대 URL 생성, 조회 및 테스트코드

be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookResponse.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- 슬라이스로 구현한 페이지네이션 기능을 페이지로 변경했습니다.
- 스크롤을 위해서 슬라이스로 페이지네이션 기능을 도입했는데, 서재라는 개념이 스크롤 보다는 페이지를 도입하는 것이 낫다고 판단하여 페이지로 바꾸기로 했습니다.
=> [BE]: 페이지네이션 수정

be/src/main/java/codesquad/bookkbookk/common/error/exception/TopicNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/CreateTopicRequest.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/CreateTopicResponse.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/ReadTopicResponse.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/UpdateTopicTitleRequest.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicRepository.java, be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java, be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- 토픽 CRUD
- 테스트코드
- 단순 CRUD입니다
=> [BE] 토픽 CRUD 기능 및 테스트 코드 구현

be/src/main/java/codesquad/bookkbookk/domain/gathering/controller/GatheringController.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/entity/Gathering.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/repository/GatheringRepository.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java
모임을 만드는 기능을 구현했습니다.
-  Gathering 엔티티 생성, GatheringRepository 생성
-  GatheringService 구현
- 책아이디로 책을 검색해서 없으면 예외를 던짐
- 회원과 책 아이디를 비교해서, 회원이 북클럽에 소속되어있지 않으면 예외를 던짐
-  GatheringController 구현
=> [BE]: 모임 생성 기능 구현

fe/src/api/book/client.ts, fe/src/api/book/queries.ts, fe/src/api/book/type.ts, fe/src/api/queryKeys.ts, fe/src/components/Library/BookList/BookCard.tsx, fe/src/components/Library/BookList/BookCardGrid.tsx, fe/src/components/Library/BookList/index.tsx, fe/src/components/NewBook/LeftBox/BookSearchStep/index.tsx, fe/src/components/NewBook/LeftBox/Modals/BookDetailModal.tsx, fe/src/components/NewBook/style.ts, fe/src/constant/index.ts, fe/src/mocks/handlers.ts, fe/src/pages/Library.tsx
=> [FE] 서재 페이지 전체 도서 목록 조회

be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterRequest.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterResponse.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/ReadChapterResponse.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/UpdateChapterTitleRequest.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterRepository.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java, be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java, be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java, be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
=> [BE]: 챕터 CRUD

be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberIsNotBookmarkWriterException.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/CreateBookmarkRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/UpdateBookmarkRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
북마크 CUD를 구현했습니다.
- 북마크의 수정, 삭제시에 동작을 시도하는 member와 북마크의 writer가 같지 않으면 예외가 발생합니다.
- 프론트와 회의를 하고 어떤 데이터를 넘겨줄 지 논의한 다음에 조회 기능을 추가하려고 합니다.
=> [BE]: Bookmark CUD 구현

be/src/main/java/codesquad/bookkbookk/common/error/exception/CommentNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberIsNotCommentWriterException.java, be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/CreateCommentRequest.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/UpdateCommentRequest.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java, be/src/main/java/codesquad/bookkbookk/domain/comment/repository/CommentRepository.java, be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java, be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
코멘트 CUD기능을 구현했습니다.
- 프론트와 회의 후 조회 기능을 구현하려고 합니다.
=> [BE] 코멘트 cud

fe/src/api/book/client.ts
=> [FE] 4주차 프론트 배포 에러 해결

be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
- 쿠키의 만료시간을 정하여 쿠키가 자동으로 만료되도록 합니다.
- 로그아웃 시 만료시간이 0인 쿠키를 넣어주어 쿠키를 자동으로 삭제하게 합니다.
=> [BE] refresh token cookie 만료시간 추가, 로그아웃 시 set-cookie 구현

be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkReactionExistsException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/BookmarkReactionNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/ReactionNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/type/Reaction.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/CreateBookmarkReactionRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/DeleteBookmarkReactionRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/BookmarkReaction.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/repository/BookmarkReactionRepository.java, be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java
=> [BE] 북마크에 반응 추가/삭제 기능 구현

be/src/main/java/codesquad/bookkbookk/common/error/exception/CommentReactionExistsException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/CommentReactionNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/CreateCommentReactionRequest.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/DeleteCommentReactionRequest.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java, be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/CommentReaction.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/repository/CommentReactionRepository.java, be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java
=> [BE] 코멘트의 반응 추가/삭제 기능 구현

fe/src/api/bookmarks/client.ts, fe/src/api/bookmarks/queries.ts, fe/src/api/comments/client.ts, fe/src/api/comments/queries.ts, fe/src/api/comments/type.ts, fe/src/api/queryKeys.ts, fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/Bookmark.tsx, fe/src/components/BookChapter/LeftBox/BookmarkList/BookmarkThread/BookmarkCommentList/BookmarkComment.tsx, fe/src/components/BookChapter/LeftBox/ChapterStatusMenu.tsx, fe/src/components/common/Comment/ActionFooter.tsx, fe/src/components/common/Comment/ReactionList/ReactionChip.tsx, fe/src/components/common/Comment/ReactionList/ReactionList.tsx, fe/src/components/common/Comment/ReactionMenu.tsx, fe/src/components/common/StatusChip.tsx, fe/src/components/constants.ts, fe/src/constant/index.ts, fe/src/mocks/data.ts
=> [FE] 북마크/댓글 리액션 기능

be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/ReadCommentResponse.java, be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java, be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
=> [BE] 코멘트 목록 조회 기능 구현

be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadReactionsResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java, be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java, be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java, be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java
Bookmark와 Comment의 Reaction을 조회합니다.
- 빠른 구현을 위해 중복 코드가 있습니다. 추후 리팩토링예정입니다.
=> [BE] Bookmark/Comment reaction 조회 기능

be/src/main/java/codesquad/bookkbookk/common/error/exception/GatheringNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/controller/GatheringController.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/ReadGatheringResponse.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/UpdateGatheringRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/UpdateGatheringResponse.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/entity/Gathering.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- gathering의 조회, 수정, 삭제 기능을 구현했습니다.
=> [BE] gathering 조회,수정, 삭제 기능 구현

fe/src/components/common/Tabs.tsx, fe/src/components/constants.ts, fe/src/pages/BookChapters.tsx
=> feat: 챕터 탭 타입 에러 수정

.github/workflows/cicd.yml, scripts/start.sh
=> [INFRA] 운영서버 배포 스크립트, workflow 변경

be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ClosedBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/OpenBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/ReadCommentResponse.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/ReadGatheringResponse.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/UpdateGatheringRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/UpdateGatheringResponse.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/entity/Gathering.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- 시간을 관리하늨 를래스를 LocalDateTime에서 Instant로 변경했습니다. 타임존의 영향을 받지 않고 UTC로 시간을 관리하도록 하기 위함입니다.
- 쿠키의 path를 추가하여 원하는 path에만 쿠키를 보내게 했습니다.
- 쿠키의 maxAge는 seconds를 입력해야 하는데 milliSeconds를 입력하여 유효기간이 매우 길었습니다. 이를 수정했습니다.
=> [BE] 시간 관리 클래스 변경 & 쿠키 옵션 추가

fe/src/api/fetcher.ts
=> hotfix: 토큰 재발급 인터셉터 일시 삭제

scripts/start-prod.sh
- dev 프로필이 아니라 prod 프로필을 사용하도록 변경했습니다.
=> fix: start-prod.sh 수정 #169

README.md
* docs: readme 수정
- 프로젝트에 관한 설명을 추가했습니다.
* docs: 프로젝트 아키텍쳐 추가
=> [BE] README 내용 추가

fe/src/api/bookClub/type.ts, fe/src/components/BookClub/LeftBox/BookClubInfo.tsx
=> [FE] BookClubDetai Status 타입 대문자로 변경

fe/src/api/bookClub/client.ts, fe/src/api/bookClub/type.ts, fe/src/components/BookClub/LeftBox/BookClubInfo.tsx
=> [FE] BookClubInfo의 status를 uppercase로 변경

README.md, be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java, be/src/main/java/codesquad/bookkbookk/common/error/ErrorResponse.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/AccessTokenIsInBlackListException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/AuthException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/BearerPrefixNotIncludedException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/MalformedTokenException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/NoAuthorizationHeaderException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/TokenExpiredException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/TokenNotIncludedException.java, be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java, be/src/main/java/codesquad/bookkbookk/common/jwt/JwtProvider.java, be/src/main/java/codesquad/bookkbookk/common/redis/RedisService.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenUuid.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenUuidArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/common/type/TokenError.java, be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/property/CookieProperty.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/AuthenticationService.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java, be/src/test/java/codesquad/bookkbookk/redis/RedisServiceTest.java
- 쿠키의 옵션을 넣어서 보안을 강화합니다.
- BookClubController의 readBookClubs에 기본 파라미터를 넣습니다.
=> [BE] BE 작업 머지

be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringsRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- CreateGatheringRequest에 하나의 모임 대신 여러 모임을 추가할 수 있도록 gatherings 필드를 만들었습니다.
=> [BE] CreateGatheringRequest에 Gatheings 필드 추가

fe/src/components/BookDetail/BookChapterListPanel/TopicItem.tsx
- TopicItem의 RecentBookmark가 없는 경우를 고려하지 않아 예외 발생하고 있습니다. 이에 수정합니다.
=> [FE] 토픽의 북마크 없는 경우 TopicItem 프린트 변경

be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadBookmarkResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java, be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java
- 토픽의 Bookmark를 조회하는 기능을 추가했습니다.
=> [BE] Topic의 Bookmark 조회 기능 추가

be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java
- Chapter Update Request의 필드가 없을 때 값을 변경하지 않도록 코드를 변경했슨디ㅏ.
=> [BE] Chapter Update 기능 변경

be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadBookmarkResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java
페이지로 북마크를 조회하는 기능을 구현했습니다.
간단하게 `@Query` 어노테이션을 사용하여서 검색 쿼리를 만들었습니다.
=> [BE] 페이지로 북마크 조회 기능

be/src/main/java/codesquad/bookkbookk/common/type/Status.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/LoginRequest.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/AuthenticationService.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/CreateBookClubRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterRequest.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterResponse.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringsRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/CreateTopicRequest.java, be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java, be/src/test/java/codesquad/bookkbookk/unit/StatusTest.java
- 서비스 레이어를 리팩토링했습니다.
- Request 객체에서 바로 Entity를 생성하도록 변경
- 서비스 레이어를 간단히 하도록 변경했습니다.
- `Status` enum에 id가 0인 경우 추가
- 서비스 레이어에서 `Status` 정보를 가지고 있을 이유가 없다고 생각하여 변경했습니다.
- CreateChapterRequest에서 DTO대신 엔티티를 반환하여 구조를 개선했습니다.
- Inner Class로 정보를 반환했었는데 필요가 없다고 생각하여 변경했습니다.
=> [BE] Service 리팩토링

be/src/main/java/codesquad/bookkbookk/common/type/Status.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/LoginRequest.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/AuthenticationService.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/CreateBookRequest.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ClosedBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/CreateBookClubRequest.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/OpenBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/type/BookClubStatus.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterRequest.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/CreateChapterResponse.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/data/dto/CreateGatheringsRequest.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/BookClubMember.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/dto/CreateTopicRequest.java, be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java, be/src/test/java/codesquad/bookkbookk/unit/StatusTest.java
=> [BE] 작업 업데이트

be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterIdExistsException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/LastInsertIdDoesNotExistException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/TopicIdExistsException.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/entity/Bookmark.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/member/data/entity/Member.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicRepository.java, be/src/main/resources/schema.sql, be/src/test/java/codesquad/bookkbookk/unit/ChapterCustomRepositoryImplTest.java
=> [BE] dev-be 머지

be/src/docs/asciidoc/index.adoc, be/src/main/java/codesquad/bookkbookk/common/error/exception/DatasourceNotConnectedException.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadBookmarkSliceResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadReactionsResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/ReadCommentSliceResponse.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java, be/src/main/java/codesquad/bookkbookk/domain/comment/repository/CommentCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/comment/repository/CommentCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepositoryImpl.java, be/src/main/resources/insertBookmarks.sql, be/src/main/resources/insertComments.sql, be/src/main/resources/schema.sql, be/src/test/java/codesquad/bookkbookk/integration/documentation/TopicDocumentationTest.java, be/src/test/java/codesquad/bookkbookk/unit/BookmarkRepositoryTest.java, be/src/test/java/codesquad/bookkbookk/unit/ChapterCustomRepositoryImplTest.java, be/src/test/java/codesquad/bookkbookk/unit/CommentRepositoryTest.java, be/src/test/resources/sql/readBookmarkSlice.sql, be/src/test/resources/sql/readCommentSlice.sql, be/src/test/resources/sql/readTopicBookmarkSlice.sql
=> [BE] 작업 머지
