bookkbookk/bookkbookk

be/src/main/java/codesquad/bookkbookk/domain/member/data/dto/MemberResponse.java, be/src/main/java/codesquad/bookkbookk/domain/member/data/entity/Member.java, be/src/main/java/codesquad/bookkbookk/domain/member/service/MemberService.java, be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
- 멤버 프로필 수정 시 요청 값 유효성 검증
- 멤버 프로필 수정 성공 시 테스트 코드
- 멤버 조회 시 응답에 email 추가
-  프로필 이미지는 기능 동작이 안되더라구요.. 그래서 테스트를 어떻게 해야할지 아직 잘 모르겠습니다
=> [BE] 멤버 프로필 수정 유효성 검증 및 테스트 코드 구현

be/src/main/java/codesquad/bookkbookk/common/config/FilterConfig.java, be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/RefreshTokenNotSavedException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/BearerPrefixNotIncludedException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/MalformedTokenException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/NoAuthorizationHeaderException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/TokenExpiredException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/jwt/TokenNotIncludedException.java, be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java, be/src/main/java/codesquad/bookkbookk/common/jwt/JwtProvider.java, be/src/main/java/codesquad/bookkbookk/common/resolver/Token.java, be/src/main/java/codesquad/bookkbookk/common/resolver/TokenArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/ReissueResponse.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/entity/MemberRefreshToken.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/entity/RefreshToken.java, be/src/main/java/codesquad/bookkbookk/domain/auth/repository/MemberRefreshTokenRepository.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/OAuthService.java, be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java, be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java
- JwtFilter와 JwtProvider를 리팩토링 했습니다.
- accessToken을 재발급 하는 기능을 구현했습니다.
- JwtFilter
- JwtFilter의 경우 예외를 처리할 때 ExceptionHandler에서 처리를 할 수 없어 HttpServletResponse.sendError() 메서드를 통해 에러 메세지를 보내주고 있었습니다. 하지만 이 경우 에러 메세지를 저희가 원하는 방식으로 보낼 수 없습니다. 그래서 직접 PrintWriter를 호출하고 에러메세지를 넣어 주었습니다.
- JWT 라이브러리에서 던지는 예외를 그대로 사용하지 않고 한번 커스터마이징을 해서 원하는 메세지를 전송하게 했습니다.
- JWT 라이브러리가 최신 버전이여서 던지는 예외의 종류가 달라졌습니다. 이에 예외를 변경했습니다.
- AccessToken 재발급
- 멤버가 로그인할 때 만들어지는 refreshToken을 member_refresh_token 테이블에 저장합니다.
- 재발급 path로 요청을 보내면 refreshToken을 받고 member_refresh_token에서 refreshToken으로 member를 찾고 찾은 member의 id로 accessToken을 만들고 반환합니다.
JwtFilter를 중점으로 보면 좋을 것 같습니다. 너무 오래걸렸네요. 코드 자체에 만족은 하는데 효율은 별로입니다.
=> [BE] JwtFilter 리팩토링, accessToken 재발급 기능 구현

be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/domain/member/controller/MemberController.java, be/src/main/java/codesquad/bookkbookk/domain/member/data/dto/UpdateProfileResponse.java, be/src/main/java/codesquad/bookkbookk/domain/member/service/MemberService.java
isEmpty가 null체크를 하지 못해서 != null로 체크
- MultipartFile null 검증 시 isEmpty가 null체크를 하지 못해서 != null 방식으로 체크
- 멤버 프로필 수정 시, 수정된 닉네임, 수정된 이미지 url을 응답하도록 변경
=> [BE] MutlipartFile null 체크 버그 수정, 멤버 프로필 수정 응답 변경

be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java
- content type을 json으로 지정해주어 해결했습니다.
=> fix: Spring Filter에서 보내는 error message 한글 깨짐 현상 해결

be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookClubBookResponse.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/member/controller/MemberController.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
- 북클럽 아이디로 책을 조회해야하기에 멤버 책 조회 기능을 Book 도메인 에서 Member 도메인으로 이식합니다.
- BookClub도메인에서 책 조회 기능을 구현합니다.
- 기존에는 bookController에서 책 조회를 관리했었습니다. 멤버의 책만 조회하기에 그렇게 하나의 Api로 조회 기능을 구현했습니다. 그런데 로직상 모임을 만들 때 북클럽의 책들도 조회하는 기능이 필요해졌습니다. 그래서 멤버의 책 조회를 MemberController에, 북클럽의 책 조회를 BookClubController에 구현했습니다.
- 쿼리 스트링으로 type을 받아서 member의 책을 조회하는 경우와 bookClub의 책을 경우를 나눌 수 있지만, 반환하는 객체의 종류가 다릅니다.(Member의 조회는 페이지, bookClubd의 조회는 슬라이스). 나중에 고민을 더 해야할 것 같은데,  일단은 빠른 구현을 위해 api를 분리했습니다.
=> [BE]: 멤버 책 조회 기능 리팩토링 & 북클럽 책 조회 기능 구현

be/src/main/java/codesquad/bookkbookk/domain/book/data/entity/Book.java, be/src/main/java/codesquad/bookkbookk/domain/book/data/type/BookStatus.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ClosedBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/OpenBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/type/BookClubStatus.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/BookClubMember.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
북클럽 상세 조회 기능을 구현했습니다.
- 북클럽이 열린 상태인지, 닫힌 상태인지에 따라서 응답의 필드가 달라집니다. 그러나 대부분의 필드가 공통이라 ReadBookClubResponse라는 조상 객체를 만들고 공통 필드를 넣은 뒤, OpenBookClubDetailResponse, ClosedBookClubDetailResponse로 각각 만들었습니다. 그래서 api의 responseEntity를 만들 때 ReadBookResponse를 body로 넣어주어 상황에 맞는 응답을 만들도록 했습니다.
- BookClubStatus에서 추상 메서드를 선언하고 각 상태마다 메서드를 구현하여 상태에 맞는 응답을 만들도록 구현했습니다.
- 가독성을 위해 ReadBookClubResponse에 inner Class를 생성했습니다.
=> [BE] 북클럽 상세 조회 기능 구현

be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/RefreshTokenNotFoundException.java, be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshToken.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/dto/LoginResponse.java, be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java
보안을 위해 refresh Token을 cookie에 담아서 반환하도록 변경합니다.
- 기존에는 refresh token을 body에 넣어 줬는데 http cookie를 사용하여 탈취에 더 안전한 구조를 만듭니다.
- 빠른 구현을 목표로 path와 expiration은 설정하지 않았습니다.
=> [BE] refresh token http-only cookie에 담아서 전달하게 코드 변경

be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterStatusNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/dto/ReadChapterResponse.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/type/ChapterStatus.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterRepository.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java, be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
프론트에서 필요한 정보를 주도록 메서드를 변경합니다.
- 엔티티 수정
- topic의 필드에 bookmark list 추가
- chapter에 status 추가
- ChpaterStatus에 statusId에 해당하는 ChapterStatus 탐색 메서드 구현
- ChapterController 수정
- ChapterService 변경
- response 객체 수정
- ChapterStatus enum에 전체에 해당하는 이넘이 없습니다. 전체를 조회하는 경우(statusId = 0)는 ChapterSeivice에서 전체를 조회합니다. 상태의 개별조회(statusId = 1, 2, 3)의 경우에서는 id에 해당하는 enum을 사용하여 Chapter를 조회합니다. ChapterStatus에 전체 enum을 추가할 수도 있었지만, 추가한다면 db에 전체에 대응하는 enum이 들어갈 수 있는 문제가 있어 Service에서 처리했습니다.
- response 객체는 innver Class를 활용하여 구현했습니다. 데이터 계층이 depth가 있어서 한번에 응답을 보기 위해 이렇게 구현했습니다. 그리고 inner Class는 private으로 지정하여 클래스 외부에서 접근이 안되게 만들었습니다.
=> [BE] 챕터 조회 기능 수정

be/src/main/java/codesquad/bookkbookk/common/error/exception/BookClubStatusNotFoundException.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ClosedBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/OpenBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/dto/ReadBookClubDetailResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/entity/BookClub.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/data/type/BookClubStatus.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/domain/member/data/entity/Member.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- 북클럽 상태를 이용하여 멤버의 북클럽을 조회합니다.
- 모든 북클럽(open과 closed 둘다)을 조회할 때 모든 상태에 해당하는 이넘을 만들지 않고 service layer에서 status를 확인하고 처리했습니다. 이것은 이넘을 추가하여 모두에 해당하는 status가 db에 저장되는 것을 방지하기 위함입니다.
=> [BE] 북클럽 상태를 이용한 북클럽 조회 구현

be/src/main/java/codesquad/bookkbookk/domain/book/data/dto/ReadBookResponse.java, be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java
-  멤버 책 조회에서 책의 statusId를 주입했습니다.
=> [BE] 멤버 책 조회에서 책의 statusId 주입

be/src/main/java/codesquad/bookkbookk/common/error/exception/MemberNotInBookClubException.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/entity/MemberRefreshToken.java, be/src/main/java/codesquad/bookkbookk/domain/auth/repository/AuthorizationRepository.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/AuthorizationService.java, be/src/main/java/codesquad/bookkbookk/domain/book/controller/BookController.java, be/src/main/java/codesquad/bookkbookk/domain/book/repository/BookRepository.java, be/src/main/java/codesquad/bookkbookk/domain/book/service/BookService.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/controller/BookClubController.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/repository/BookClubRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/controller/BookmarkController.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/controller/ChapterController.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/comment/controller/CommentController.java, be/src/main/java/codesquad/bookkbookk/domain/comment/service/CommentService.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/controller/GatheringController.java, be/src/main/java/codesquad/bookkbookk/domain/gathering/service/GatheringService.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/BookClubMember.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/CommentReaction.java, be/src/main/java/codesquad/bookkbookk/domain/mapping/entity/MemberBook.java, be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java, be/src/main/java/codesquad/bookkbookk/domain/topic/service/TopicService.java, be/src/test/java/codesquad/bookkbookk/auth/repository/AuthorizationRepositoryTest.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java, be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java, be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java, be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java
인가 기능을 추가했습니다.
- JpaRepository에서 제공하는  exists 메서드를 사용하면 불필요한 join이 발생합니다.  또한 exists 메서드가 인가 작업에만 존재하기에 AuthorizationRepository를 생성하여 쿼리를 만들었습니다.
- Service 계층에서 memberId를 매개변수로 받지 않는 경우가 있습니다. 인가 기능을 사용하기 위해 Service의 parameter를 수정했습니다.
- reaction 삭제의 경우는 BookClub 멤버를 확인하지 않고 작성자임만을 확인합니다. 이는 작성시에 확인하기 때문입니다.
=> BE: 인가 기능 추가

be/src/test/java/codesquad/bookkbookk/auth/repository/AuthorizationRepositoryTest.java, be/src/test/java/codesquad/bookkbookk/book/integration/BookTest.java, be/src/test/java/codesquad/bookkbookk/bookclub/integration/BookClubTest.java, be/src/test/java/codesquad/bookkbookk/bookmark/integration/BookmarkTest.java, be/src/test/java/codesquad/bookkbookk/chapter/integration/ChapterTest.java, be/src/test/java/codesquad/bookkbookk/comment/integration/CommentTest.java, be/src/test/java/codesquad/bookkbookk/gathering/integration/GatheringTest.java, be/src/test/java/codesquad/bookkbookk/member/integration/MemberTest.java, be/src/test/java/codesquad/bookkbookk/topic/integration/TopicTest.java, be/src/test/java/codesquad/bookkbookk/util/TestDataFactory.java
- Dummy data 생성 메서드에 parameter로 number를 입력받아 data를 만들도록 변경
- CreateBook 메서드의 creatorId 하드코딩 삭제
- 기존에는 테스트 코드의 TestDataFactory에 하드코딩 된 부분이 많았습니다. 하드코딩을 지웠습니다.
- 똑같은 객체를 만드는 메서드가 중복해서 있어 중복을 없앴습니다.
=> [BE} 테스트 코드 리팩토링

be/src/main/java/codesquad/bookkbookk/domain/bookclub/service/BookClubService.java
- memberId 대신 bookClubId를 넣게 했습니다.
=> [BE] bookClub 생성 기능 오류 해결

be/src/main/java/codesquad/bookkbookk/common/error/ErrorResponse.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/AccessTokenIsInBlackListException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/AuthException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/BearerPrefixNotIncludedException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/MalformedTokenException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/NoAuthorizationHeaderException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/TokenExpiredException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/auth/TokenNotIncludedException.java, be/src/main/java/codesquad/bookkbookk/common/filter/JwtFilter.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/common/type/TokenError.java, be/src/test/java/codesquad/bookkbookk/filter/FilterTest.java
- JwtFilter에 있는 하드코딩 되어있는 String 중 일부를 의미 있는 코드로 변경했습니다.
- 4012, 4011로Access Token에서 발생하는 오류와 Refrest Token에서 발생하는 오류를 구분했는데 좀 더 의미있는 코드가 되기 위해 숫자 대신 enum을 도입했습니다.
=> [BE] JwtFilter String 하드 코딩 삭제 && TokenError enum 생성

be/src/main/java/codesquad/bookkbookk/common/config/WebConfig.java, be/src/main/java/codesquad/bookkbookk/common/jwt/JwtProvider.java, be/src/main/java/codesquad/bookkbookk/common/redis/RedisService.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenUuid.java, be/src/main/java/codesquad/bookkbookk/common/resolver/RefreshTokenUuidArgumentResolver.java, be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/auth/service/AuthenticationService.java, be/src/test/java/codesquad/bookkbookk/auth/integration/AuthTest.java, be/src/test/java/codesquad/bookkbookk/redis/RedisServiceTest.java
- Refresh Token의 Payload에 uuid를 추가하여 유일성을 보장했습니다.
- 유일성을 보장하기 위해서 uuid를 고민했습니다. 이 과정에서 Refresh Token이 굳이 JWT 형식이여야 하나 고민했습니다만, 그냥 uuid로 통신하게 되면 DB에 부담될 수 있어서 JWT의 Payload에 uuid를 넣었습니다.
=> [BE] Refresh Token에 UUID 필드 추가

be/src/main/java/codesquad/bookkbookk/domain/auth/controller/AuthController.java, be/src/main/java/codesquad/bookkbookk/domain/auth/data/property/CookieProperty.java
Http Cookie의 옵션을 프로필에 따라 다르게 설정할 수 있게 변경합니다.
개발 서버와 운영 서버의 secure 옵션이 달라야 한다고 생각해서 변경했습니다.
개발 서버의 경우 도메인이 없어 http로 통신하는데 반해 운영 서버는 도메인을 구입해서 https 프로토콜을 사용합니다.
코드가 `secure` 옵션을 사용하지 않도록 일원화 되어있는데, 개발 서버, 로컬, 운영 서버를 구분해서 운영 서버에서는 `secure` 옵션을 사용해 보안을 강화했습니다.
=> [BE] 프로필에 따른 Http Cookie의 옵션 다양화

fe/src/components/BookDetail/BookChapterListPanel/ChapterItem.tsx, fe/src/components/BookDetail/BookChapterListPanel/TopicItem.tsx
- 이슈: #214
- nodeId에 prefix를 붙여서 유일성을 보장했습니다.
=> [FE] BookDetail에서 ChapterItem tree 랜더링 오류  해결

be/src/test/java/codesquad/bookkbookk/integration/documentation/BookDocumentationTest.java, be/src/test/java/codesquad/bookkbookk/integration/scenario/BookTest.java, be/src/test/java/codesquad/bookkbookk/util/IntegrationTest.java
- `JdbcTemplate` 대신 `@Sql`을 사용하여 데이터를 넣습니다.
- 테스트 메서드 안에 `JdbcTemplate`를 사용하는 것보다 `@Sql`을 사용하여 테스트 로직과 관련 없이 셋팅하는 것이 가독성 면에서 좋다고 생각하여 변경했습니다.
- `@Sql`보다 `IntegrationTest.setUp()` 메서드가 뒤에 작동하여 데이터를 넣어도 초기화되는 문제가 있었습니다. DB 초기화를 테스트 메서드 후에 동작하게 변경했습니다.
=> [BE] `@Sql` 사용하여 테스트 데이터 입력하기

be/src/main/java/codesquad/bookkbookk/common/error/exception/ChapterIdExistsException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/LastInsertIdDoesNotExistException.java, be/src/main/java/codesquad/bookkbookk/common/error/exception/TopicIdExistsException.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/data/entity/Chapter.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/topic/data/entity/Topic.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicRepository.java, be/src/test/java/codesquad/bookkbookk/unit/ChapterCustomRepositoryImplTest.java
- `Chapter`와 `Topic`을 Batch Insert하고 아이디를 주입하는 기능을 만들었습니다.
- Batch Insert 관련
- 엔티티의 Id 생성 전략이 `Identity`로 DB에 책임이 있기에  JPA에서 제공해주는 Batch Insert는 사용할 수 없습니다.
- 그렇다면 3가지 가능성이 있습니다.
- `EntityManager. createNativeQuery()` 메서드를 활용
- `JdbcTemplate.batchUpdate()` 메서드를 활용
- `NamedParameterJdbcTemplate.batchUpdate()` 메서드를 활용
- 이중에서 `NamedParameterJdbcTemplate`를 사용하여 파라미터가 매핑 될 때 순서가 아닌 변수명으로 관리하기 위함입니다.
- `LAST_INSERT_ID()`관련
- Batch Insert를 할 때 아이디가 순차적으로 부여되는가
- Mysql 공식문서에 따르면 이런 INSERT는 SImple Insert입니다. 그리고 Inno DB의 `AUTO_INCREMENT` 기본 락은 `interleaved lock mode`이고 Simple Insert에 대해서 순차적으로 아이디가 부여됨을 보장합니다.
- `LAST_INSERT_ID()`가 영향을 받을 가능성은 없는가
- `LAST_INSERT_ID()`는 db connection의 마지막 INSERT ID를 불러오고, 다른 connection의 영향을 받지 않습니다. 따라서 `LAST_INSET_ID()`는 Batch Insert 다음에 쓰인다면 다른 값이 들어갈 가능성이 없습니다.
=> [BE] `Chapter`, `Topic` Batch Insert 기능 구현

be/src/main/java/codesquad/bookkbookk/common/error/exception/DatasourceNotConnectedException.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/repository/ChapterCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/chapter/service/ChapterService.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/topic/repository/TopicCustomRepositoryImpl.java
- NamedParameterJdbcTemplate대신 JdbcTemplate를 사용하여 Batch Insert 기능을 구현했습니다.
- `NamedParameterJdbcTemplate.batchUpdate()`메서드 대신 Batch Insert 쿼리를 직접 작성하여 구현했습니다.
- 테스트 DB(H2), 와 운영DB(Mysql)을 구분하여서 Id를 주입하는 방법을 변경했습니다.
- NamedParameterJdbcTemplate대신 JdbcTemplate를 사용 & 쿼리를 직접 만듬
- `JdbcTemplate.batchUpdate()`를 사용하여 Batch Insert하기 위해선 Mysql의 옵션이 필수적입니다. 이렇게 코드를 짜게 된다면 DB에 종속적이게 되어 DB를 변경할 때 힘들어집니다. 따라서 쿼리를 직접 작성하고 JdbcTemplate를 사용하여 쿼리를 실행합니다.
- 쿼리를 실행시킬 떄 EntityManager과 JdbcTemplate 두 가지 방법이 있다고 생각하는데, `LAST_INSERT_ID()`가 DB의 종류에 따라 다르게 동작합니다. EntityManager에서는 DB의 종류를 알 수 없기에, JdbcTemplate를 사용했습니다.
=> [BE] Batch Insert 기능이 DB에 의존적이지 않도록 리팩토링

be/src/docs/asciidoc/index.adoc, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadBookmarkSliceResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/data/dto/ReadReactionsResponse.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/repository/BookmarkCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/bookmark/service/BookmarkService.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/dto/ReadCommentSliceResponse.java, be/src/main/java/codesquad/bookkbookk/domain/comment/data/entity/Comment.java, be/src/main/java/codesquad/bookkbookk/domain/comment/repository/CommentCustomRepository.java, be/src/main/java/codesquad/bookkbookk/domain/comment/repository/CommentCustomRepositoryImpl.java, be/src/main/java/codesquad/bookkbookk/domain/topic/controller/TopicController.java, be/src/main/resources/insertBookmarks.sql, be/src/main/resources/insertComments.sql, be/src/main/resources/schema.sql, be/src/test/java/codesquad/bookkbookk/integration/documentation/TopicDocumentationTest.java, be/src/test/java/codesquad/bookkbookk/unit/BookmarkRepositoryTest.java, be/src/test/java/codesquad/bookkbookk/unit/ChapterCustomRepositoryImplTest.java, be/src/test/java/codesquad/bookkbookk/unit/CommentRepositoryTest.java, be/src/test/resources/sql/readBookmarkSlice.sql, be/src/test/resources/sql/readCommentSlice.sql, be/src/test/resources/sql/readTopicBookmarkSlice.sql
- Bookmark와 Comment를 Slice해서 가져옵니다.
- 기존의 코드에서는 Bookmark, Comment, Reaction 개수만큼 api 요청이 갑니다. 첫 화면을 보여주기 위해서 한번에 정보를 넘겨줍니다.
- Slice를 적용해서 한번에 모든 정보를 보여주지 않습니다.
- Bookmark를 슬라이스를 할 때 JPA를 사용했기에, Bookmark Wirter과 Bookmark Reaction을 초기화하는 쿼리가 각각 나갑니다.
- Bookmark를 가져올 때 쿼리가 3번 나갑니다.
- Bookmark 정보를 가져오는 쿼리(ORDER BY 와 LIMIT로 제한하기에 Reaction과 따로 보냄)
- Bookmark Reaction의 정보를 가져오는 쿼리
- Bookmark Reaction Reactor의 정보를 가져오는 쿼리
- Comment를 슬라이스 할떄는 `ROW_NUM()` 프로시저를 사용했기에 JdbcTemplate를 사용했습니다.
- 또한 엔티티를 가져온 다음에 DTO로 변환하는게 아니라 `ResultSet`에서 바로 DTO로 변환합니다.
- Comment를 가져올 때 2번의 쿼리가 나갑니다.
- Comment 정보를 가져오는 쿼리
- Comment Reaction 정보를 가져오는 쿼리
=> [BE] Bookmark, Comment, Reaction 한번에 가져오기 & Slice 적용하기
